[package]
name = "advent-of-code-2023"
version = "0.1.0"
edition = "2021"

[dependencies]
counter = "0.5.7"
num = "0.4.1"
rangemap = "1.4.0"
regex = "1.10.2"
regex-macro = "0.2.0"
itertools = "0.12.0"
test-case = "3.3.1"
